### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by iam-py-test** [ad-m/report-link-action#6]
I am sorry that I lack more information such as steps to reproduce or why this happened, but it seems that this action reported a working link in my repo as broken. (https://github.com/iam-py-test/my_filters_001/issues/93)
Going directly to the link shows it works fine, so I am confused.

**Comment by ad-m** [comment]
Oh, I was not aware that anybody is using that action 😺  Unfortunately, I don't have details of broken link ( https://github.com/iam-py-test/my_filters_001/runs/4641968880?check_suite_focus=true ) due to a bug in logging ( 04b0789 ). Could you rerun any run of workflow https://github.com/iam-py-test/my_filters_001/actions/workflows/links.yml ?

**Comment by iam-py-test** [comment]
When I reran it, it closed the issue

**Comment by iam-py-test** [comment]
Seems like a momentary glitch
